### ISSUE TITLE
ie8 and ie9  APPCRASH 

### ISSUE THREAD

**Issue by chuanhaisoft** [gimite/web-socket-js#176]
modify:

!DOCTYPE html PUBLIC"_//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/ahtml1-strict.dtd"
html xmlns="http://www.w3.org/1999/xhtml"

then:

  问题事件名称:	APPCRASH
  应用程序名:	iexplore.exe
  应用程序版本:	9.0.8112.16684
  应用程序时间戳:	55b000e5
  故障模块名称:	ykcool.dll
  故障模块版本:	2.5.0.11110
  故障模块时间戳:	567b9c5c
  异常代码:	c0000005
  异常偏移:	000247bc
  OS 版本:	6.1.7601.2.1.0.274.10
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by chuanhaisoft** [comment]
0x647247BC (ykcool.dll) (iexplore.exe 中)处有未经处理的异常:  0xC0000005:  读取位置 0x00000000 时发生访问冲突。

**Comment by gimite** [comment]
Seeing the error message, the crash is happening inside ykcool.dll, which seems like Youku BHOPlugin:
http://www.freefixer.com/library/file/ykcool.dll-225924/

So it's quite likely caused by the plugin, because web-socket-js doesn't depend on the plugin.

Try uninstalling the plugin, or report the issue to the author of the plugin.
